spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.105.202.152/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 99Liyisong0526!
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  level:
    root: warn
    com.lys: info
  file: log/blog-pro.log






